#!/usr/bin/env bash

#
# This is a shell script for using the Nautilus cluster at https://nautilus.optiputer.net
#

getopt --test > /dev/null
if [[ $? -ne 4 ]]; then
    echo "I’m sorry, `getopt --test` failed in this environment."
    exit 1
fi

OPTIONS=dfo:v
LONGOPTIONS=debug,force,output:,verbose

# -temporarily store output to be able to check for errors
# -e.g. use “--options” parameter by name to activate quoting/enhanced mode
# -pass arguments only via   -- "$@"   to separate them correctly
PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTIONS --name "$0" -- "$@")
if [[ $? -ne 0 ]]; then
    # e.g. $? == 1
    #  then getopt has complained about wrong arguments to stdout
    exit 2
fi
# read getopt’s output this way to handle the quoting right:
eval set -- "$PARSED"

# now enjoy the options in order and nicely split until we see --
while true; do
    case "$1" in
        -y|--yaml)
            YAML=y
            shift
            ;;
        -g|--gpus)
            GPUS=g
            shift
            ;;
        -c|--cpus)
            CPUS=c
            shift
            ;;
        -m|--mem)
            MEM=m
            shift
            ;;
	-s|--sync)
	    SYNC_FROM=${SYNC_FROM}:${2}
	    SYNC_TO=${SYNC_TO}:${2}
	    shift 2
	    ;;
        --)
            shift
            break
            ;;
        *)
            echo "Programming error"
            exit 3
            ;;
    esac
done

# handle non-option arguments
if [[ $# -ne 1 ]]; then
    echo "Options: --yaml ${YAML} --gpus ${GPUS} --cpus ${CPUS} --mem ${MEM} --sync ${SYNC}"
    echo "Run command: $0"
    exit 4
fi

echo "END"
