#!/usr/bin/env bash

#
# Documentation at: https://github.com/davidparks21/nautilus_cluster_control
# This is a shell script for using the Nautilus cluster at https://nautilus.optiputer.net
#

# TODOs / Issues:
#   - `narun --gpu` will cause the command line parsing to go into an infinite loop, fix this

#
# Global script defaults
#
YAML=TODO_ADD_DEFAULT.yaml
GPU=0
CPU=4
MEM=4GB

#
# Functions below implement the various components of the script
#
na_run_script(){
    echo "TODO - Launch POD and connect to process"
    echo "ARGS: YAML=$YAML GPU=$GPU CPU=$CPU MEM=$MEM SYNC_FROM=$SYNC_FROM SYNC_TO=$SYNC_TO"
}

#
# Command line parsing
#
PARAMS=""

while (( "$#" )); do
    case "$1" in
        -y|--yaml)
            YAML=$2
            shift 2
            ;;
        -g|--gpu)
            GPUS=$2
            shift 2
            ;;
        -c|--cpu)
            CPUS=$2
            shift 2
            ;;
        -m|--mem)
            MEM=$2
            shift 2
            ;;
        -s|--sync)
            SYNC_FROM=${SYNC_FROM}:${2}
            SYNC_TO=${SYNC_TO}:${3}
            shift 3
            ;;
        --) # end argument parsing
            shift
            break
            ;;
        -*|--*=) # unsupported flags
            echo "Error: Unsupported flag $1" >&2
            exit 1
            ;;
        *) # preserve positional arguments
            PARAM="$PARAMS $1"
            shift
            ;;
    esac
done

# set positional arguments in their proper place
eval set -- "$PARAMS"

na_run_script