#!/usr/bin/env bash

#
# Documentation at: https://github.com/davidparks21/nautilus_cluster_control
# This is a shell script for using the Nautilus cluster at https://nautilus.optiputer.net
#

# TODOs / Issues:
#   - `navolume --anyparam` will cause the command line parsing to go into an infinite loop, fix this

#
# Global script defaults
#
VOLUME_NAME=MYVOLUME
VOLUME_SIZE=20GB

#
# Functions below implement the various components of the script
#
navolume_create(){
    echo "TODO - Create a new volume"
    echo "ARGS: YAML=$YAML GPU=$GPU CPU=$CPU MEM=$MEM SYNC_FROM=$SYNC_FROM SYNC_TO=$SYNC_TO"
}

#
# Command line parsing
#
PARAMS=""

while (( "$#" )); do
    case "$1" in
        create)
            YAML=$2
            shift 2
            ;;
        sync)
            GPU=$2
            shift 2
            ;;
        list)
            CPU=$2
            shift 2
            ;;
        delete)
            MEM=$2
            shift 2
            ;;
        -s|--sync)
            SYNC_FROM=${SYNC_FROM}:${2}
            SYNC_TO=${SYNC_TO}:${3}
            shift 3
            ;;
        --) # end argument parsing
            shift
            break
            ;;
        -*|--*=) # unsupported flags
            echo "Error: Unsupported flag $1" >&2
            exit 1
            ;;
        *) # preserve positional arguments
            PARAM="$PARAMS $1"
            shift
            ;;
    esac
done

# set positional arguments in their proper place
eval set -- "$PARAMS"

run_script